### ISSUE TITLE
Progress Tracker: Heap & Node class methods

### ISSUE THREAD

**Issue by klaudiosinani** [klaussinani/binoheap#3]
## Description

Progress tracking **thread** regarding the implementation of the exposed `Heap` & `Node` class methods.

### Heap Methods

- [x] `Heap#head`
- [x] `Heap#size`
- [x] `Heap#clear()`
- [x] `Heap#extremum()`
- [x] `Heap#extremumKey()`
- [x] `Heap#extremumValue()`
- [x] `Heap#heapTrees()`
- [x] `Heap#includes(key)`
- [x] `Heap#insert(key, value)`
- [x] `Heap#isEmpty()`
- [x] `Heap#merge(heap)`
- [x] `Heap#removeExtremum()`
- [x] `Heap#roots()`
- [x] `Heap#search(key)`
- [x] `Heap#updateKey(key, newKey)`

### Node Methods

- [x] `Node#key`
- [x] `Node#value`
- [x] `Node#degree`
- [x] `Node#parent`
- [x] `Node#child`
- [x] `Node#sibling`
- [x] `Node#descendants()`
- [x] `Node#siblings()`
- [x] `Node#toPair()`
